<?php
define("DB_HOST", "localhost");                           // 호스트명
define("DB_ID", "dymarket");                          		     // 디비 아이디   
define("DB_PASSWORD", "a1s2d3f4");          // 디비 비밀번호
define("DB_NAME", "dymarket");                             // db 이름

/*
 * 이미지 설정
 */
define("IMAGE_FILE_PATH", "../images/");	// 이미지 파일 path
define("THUMBNAILS_FILE_PATH", "../images/thumbnails/");	// 썸네일 이미지
define("WIDTH_RESIZE", 1500);				// 이미지 최대 가로 값 
define("HEIGHT_RESIZE", 1500);			// 이미지 최대  세로값
define("THUMBNAILS_RESIZE", 150);	// 썸네일 이미지 리사이즈값

define("TITLE", "게시판");

